Globomantics/Controllers/ConferenceController.cs
using Globomantics.Client.ApiServices;
using Globomantics.Client.Models;
using Microsoft.AspNetCore.Mvc;

namespace Globomantics.Controllers;

public class ConferenceController : Controller
{
    private readonly IConferenceApiService _ApiService;

    public ConferenceController(IConferenceApiService service)
    {
        _ApiService = service;
    }

    public async Task<IActionResult> Index()
    {
        ViewBag.Title = "Organizer - Conference Overview";
        return View(await _ApiService.GetAll());
    }

    public IActionResult Add()
    {
        ViewBag.Title = "Organizer - Add Conference";
        return View(new ConferenceModel());
    }

    [HttpPost]
    public async Task<IActionResult> Add(ConferenceModel model)
    {
        if (ModelState.IsValid)
            await _ApiService.Add(model);

        return RedirectToAction("Index");
    }
}

Globomantics/Controllers/ProposalController.cs
using Globomantics.Client.ApiServices;
using Globomantics.Client.Models;
using Microsoft.AspNetCore.Mvc;

namespace Globomantics.Controllers;
public class ProposalController : Controller
{
    private readonly IConferenceApiService _ConferenceApiService;
    private readonly IProposalApiService _ProposalApiService;

    public ProposalController(IConferenceApiService conferenceApiService, IProposalApiService proposalApiService)
    {
        _ConferenceApiService = conferenceApiService;
        _ProposalApiService = proposalApiService;
    }

    public async Task<IActionResult> Index(int conferenceId)
    {
        var conference = await _ConferenceApiService.GetById(conferenceId);
        ViewBag.Title = $"Speaker - Proposals For Conference {conference.Name} {conference.Location}";
        ViewBag.ConferenceId = conferenceId;

        return View(await _ProposalApiService.GetAll(conferenceId));
    }

    public IActionResult AddProposal(int conferenceId)
    {
        ViewBag.Title = "Speaker - Add Proposal";
        return View(new ProposalModel { ConferenceId = conferenceId });
    }

    [HttpPost]
    public async Task<IActionResult> AddProposal(ProposalModel proposal)
    {
        if (ModelState.IsValid)
            await _ProposalApiService.Add(proposal);
        return RedirectToAction("Index", new { conferenceId = proposal.ConferenceId });
    }

    public async Task<IActionResult> Approve(int proposalId)
    {
        var proposal = await _ProposalApiService.Approve(proposalId);
        return RedirectToAction("Index", new { conferenceId = proposal.ConferenceId });
    }
}

Globomantics/Views/Conference/Add.cshtml
@using Globomantics.Client.Models;
@model ConferenceModel
<form asp-action="Add">
    <div class="row form-group">
        <div class="col-md-2 col-md-offset-2">
            <label asp-for="Name"></label>
        </div>
        <div class="col-md-2">
            <input class="form-control" asp-for="Name" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 col-md-offset-2">
            <label asp-for="Location"></label>
        </div>
        <div class="col-md-2">
            <input class="form-control" asp-for="Location" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 col-md-offset-2">
            <label asp-for="Start"></label>
        </div>
        <div class="col-md-2">
            <input class="form-control" type="date" asp-for="Start" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 col-md-offset-4">
            <button type="submit" class="btn btn-primary">Add</button>
        </div>
    </div>
</form>

Globomantics/Views/Conference/Index.cshtml
@model IEnumerable<Globomantics.Client.Models.ConferenceModel>
<div class="row">
    <div class="col-12">
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Location</th>
                <th>Start of event</th>
                <th>Attendees</th>
                <th>Actions</th>
            </tr>
            @foreach (var conference in Model)
            {
                <tr>
                    <td>@conference.Name</td>
                    <td>@conference.Location</td>
                    <td>@conference.Start.ToString("ddd d MMM")</td>
                    <td>@conference.AttendeeCount</td>
                    <td>
                        <a asp-controller="Proposal" asp-action="Index" asp-route-conferenceId="@conference.Id">Proposals</a>
                    </td>
                </tr>
            }
        </table>
        <a asp-action="Add">Add</a>
    </div>
</div>

@if (User.Identity != null && User.Identity.IsAuthenticated)
{
    <table class="table table-sm">
        @foreach (var claim in User.Claims)
        {
            <tr>
                <td>@claim.Type</td>
                <td>@claim.Value</td>
            </tr>
        }
    </table>
}

Globomantics/Views/Proposal/AddProposal.cshtml
@model Globomantics.Client.Models.ProposalModel
<form asp-action="AddProposal">
    <input type="hidden" asp-for="ConferenceId"/>

    <div class="row form-group">
        <div class="col-md-2 col-md-offset-2">
            <label asp-for="Title"></label>
        </div>
        <div class="col-md-2">
            <input class="form-control" asp-for="Title"/>
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 col-md-offset-2">
            <label asp-for="Speaker"></label>
        </div>
        <div class="col-md-2">
            <input class="form-control" asp-for="Speaker"/>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 col-md-offset-4">
            <button type="submit" class="btn btn-primary">Add</button>
        </div>
    </div>
</form>

Globomantics/Views/Proposal/Index.cshtml
@model IEnumerable<Globomantics.Client.Models.ProposalModel>
<div class="row">
    <div class="col-md-10 col-md-offset-2">
        <table class="table">
            <tr>
                <th>Title</th>
                <th>Speaker</th>
                <th>Approved</th>
                <th>Actions</th>
            </tr>
            @foreach (var proposal in Model)
            {
                <tr>
                    <td>@proposal.Title</td>
                    <td>@proposal.Speaker</td>
                    <td>
                        @if (proposal.Approved)
                        {
                            <div>Yes</div>
                        }
                    </td>
                    <td>
                        @if (!proposal.Approved)
                        {
                            <a asp-action="Approve" asp-route-proposalId="@proposal.Id">Approve</a>
                        }
                    </td>
                </tr>
            }
        </table>
        <a asp-action="AddProposal" asp-route-conferenceId="@ViewBag.ConferenceId">Add</a>

    </div>
</div>

Globomantics/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-12 mt-2 ml-n2">
                <img width="500px" src="~/img/globomantics-logo-darkblue.png" style="max-width:100%" />
            </div>
            </div>
            <div class="row">
            <div class="col-7 mt-2 mb-2">
                <span class="text-primary">@ViewBag.Title</span>
            </div>
        </div>
        <div>
            @RenderBody()
        </div>
    </div>
</body>

@RenderSection("scripts", false)
</html>